packages:
  - layers/*
  - packages/*
  - website
catalog:
  '@total-typescript/ts-reset': ^0.5.1
  '@total-typescript/tsconfig': ^1.0.4
  nuxt: ^3.12.4
  tsup: ^8.2.4
  typescript: ^5.5.4
  vitest: ^2.0.5
  vue: ^3.4.38
