name: Continuous integration

on:
  pull_request:
    branches:
      - main

  push:
    branches:
      - main

concurrency:
  cancel-in-progress: true
  group: ci-${{ github.event.pull_request.number || github.ref }}

env:
  NODE_OPTIONS: --max-old-space-size=6144
  COMMIT_SHA: ${{ github.event_name == 'pull_request' && github.event.pull_request.head.sha || github.sha }}

jobs:
  lint:
    runs-on: ubuntu-latest

    environment: Testing

    steps:
      - uses: actions/checkout@v4
      - uses: ./.github/actions/setup-and-cache

      - name: Install dependencies
        run: pnpm install

      - name: Lint code with ESLint
        run: pnpm run --filter website lint

  typecheck:
    runs-on: ubuntu-latest

    environment: Testing

    steps:
      - uses: actions/checkout@v4
      - uses: ./.github/actions/setup-and-cache

      - name: Install dependencies
        run: pnpm install

      - name: Typecheck
        run: pnpm run --filter website typecheck

  test:
    runs-on: ubuntu-latest

    environment: Testing

    steps:
      - uses: actions/checkout@v4
      - uses: ./.github/actions/setup-and-cache

      - name: Install dependencies
        run: pnpm install

      - name: Test
        if: github.event_name == 'pull_request'
        run: pnpm run --filter website test --coverage --changed ${{ env.COMMIT_SHA }}

      - name: Test
        if: github.event_name == 'push'
        run: pnpm run --filter website test --coverage
